name: deploy-docusaurus

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      # Checkout code
      - name: Check out repo
        uses: actions/checkout@v2

      # Setup Node.js
      - name: Set up Node
        uses: actions/setup-node@v2
        with:
          node-version: 18

      # 🔍 Snyk Scan (inside 'website' folder)
      - name: Install Snyk CLI
        run: npm install -g snyk

      - name: Run Snyk scan
        run: |
          cd website
          yarn remove react-helmet-async
          yarn add react-helmet-async@npm:@slorber/react-helmet-async@1.3.0
          snyk monitor
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}

      # Install dependencies and build Docusaurus
      - name: Build Docusaurus website
        run: |
          cd website
          npm install
          npm run build

      # Deploy to GitHub Pages
      - name: Deploy to GitHub Pages
        if: success()
        uses: crazy-max/ghaction-github-pages@v2
        with:
          target_branch: gh-pages
          build_dir: website/build
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
